#!/bin/bash

o="$(curl --silent --compressed wttr.in/~59.9387318,30.3162286?format="%C:%f\n")"

declare -A icons=(
  ["sunny"]=""
  ["clear"]=""
  ["clear/sunny"]=""
  ["cloudy"]=""
  ["partly cloudy"]=""
  ["parftial fog, fog"]=""
)

condition="$(awk -F":" '{ print tolower($1) }' <<< "$o")"
feels_like="$(awk -F":" '{ print $2 }' <<< "$o")"

echo "$condition ${icons[$condition]} "
