#!/bin/bash

read -d '' not_terminal << EOF
discord
brave
EOF

read -d '' terminal << EOF
sdlfasldfja
EOF

read -d '' browser << EOF
unixporn
all
funny
mechanicalkeyboards
EOF

# remember to set a floating rule in the wm
WINDOW_NAME="launcher"

_init() {
  xdotool search --onlyvisible --classname $WINDOW_NAME windowunmap \
    || xdotool search --classname $WINDOW_NAME windowmap \
    || st -n $WINDOW_NAME -a -g "75x7+0+0" -e "$0" "$@"
}

_fzf_preview() {
#  get() {
#    echo $2
#  }
#  echo $(get $(decide $1))
  echo $(decide "$1")
}

_fzf() {
  fzf +m \
    --preview="echo '$(decide {})'" --preview-window=right:30:noborder:wrap \
    --reverse --no-info --margin 2 --prompt="$ " \
    --color="bg:-1,bg+:-1,gutter:-1,hl:15,hl+:15,fg:7,fg+:7,prompt:2,pointer:8,header:7,preview-fg:8" \
    "$@"
}

_get_choices() {
  local choices
  #choices+=$(compgen -c)
  #choices+=$(ls -A)
  #choices+=""
  choices+=$browser
  #printf '%s\n' "$choices"
  $(printf '%s\n' "$browser")
}

decide() {
  if $(printf "%s\n" "$browser" | grep -q $1); then
    echo "|unixporn|"
    echo -e "|$1|"
  fi
}

decide1() {
  if $(echo "$browser" | grep -q "^$1$"); then
    echo "$1" "web"
#    if [[ "$1" == "r/"* ]]; then
#      echo "reddit.com/""$1" "web"
#    else
#    fi
  elif $(echo "$not_terminal" | grep -q "^$1$"); then
    echo "$1" "gui"
  elif $(echo "$terminal" | grep -q "^$1$"); then
    echo "$1" "term"
  else
    files=$(find /usr/share/applications/ -maxdepth 1 -type f -name '*.desktop' | sort | awk -F/ '{print $NF}' | cut -d'.' -f1)
    if $(echo "$files" | grep -q "^$1$"); then
      if grep -q "Terminal=false" /usr/share/applications/"$1".desktop; then
        echo "$1" "gui"
      else
        echo "$1" "term"
      fi
    else
      echo "$1" "default"
    fi
  fi
}

# launch applications based on the above
_run_application() {

  _detach_process() {
    exec setsid "$@"
  }

  _is_terminal() {
    if $(echo "$not_terminal" | grep -q "^$1$"); then
      return 1
    elif $(echo "$terminal" | grep -q "^$1$"); then
      return 0
    else
      files=$(find /usr/share/applications/ -maxdepth 1 -type f -name '*.desktop' | sort | awk -F/ '{print $NF}' | cut -d'.' -f1)
      if $(echo "$files" | grep -q "^$1$"); then
        if grep -q "Terminal=false" /usr/share/applications/"$1".desktop; then
          return 1 #false
        else
          return 0 #true
        fi
      else
        return 0
      fi
    fi
  }

  if $(_is_terminal "$1"); then
#    echo "$1 is terminal"
#    sleep 1s
    _detach_process st -e "$1"
  else
#    echo "$1 is not terminal"
#    sleep 1s
    _detach_process "$1"
  fi

#  case "$2" in
#    gui)
#      _detach_process "$1"
#      ;;
#    term)
#      _detach_process st -e "$1"
#      ;;
#    web)
#      _detach_process brave "$1"
#      ;;
#    esac
}

case "$1" in
  _run)
    choice=$(_get_choices | _fzf) && _run_application "$choice"
    ;;
#  run)
#    _init _run
#    ;;
  *)
    _init _run
    echo "noarg"
    exit 1
    ;;
esac

# run .desktop files
#`grep '^Exec' filename.desktop | tail -1 | sed 's/^Exec=//' | sed 's/%.//' | sed 's/^"//g' | sed 's/" *$//g'`
