#!/bin/bash

bb(){
    cd ~/blueberry
    if [ $# -ne 0 ]; then
       vim ~/blueberry/$1
    fi 
}

# nvim
alias v='nvim'

# launch nvim in term emus, vim otherwise
vim(){
    shopt -q login_shell && vim ${1} || nvim ${1}
}


# xflux
alias flux='xflux -l 60 -g 30 -k 3200'

# list
alias ls='ls --color=auto'
alias la='ls -a'
alias ll='ls -la'
alias l='ls' 					
alias l.='ls -A | egrep "^\."'      

# cd
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# fix obvious typos
alias cd..='cd ..'
alias pdw='pwd'

#shopt
shopt -s cdspell # autocorrects cd typos
shopt -s dotglob # include .files in the expansion
shopt -s expand_aliases # expand aliases
shopt -s nocaseglob # case-insensitive expansion

shopt -s histappend # do not overwrite history
shopt -s cmdhist # save multi-line commands in history as single line

shopt -s autocd # change to named directory

# --- dark forest ---

## Colorize the grep command output for ease of use (good for log files)##
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

#readable output
alias df='df -h'

#pacman unlock
alias unlock='sudo rm /var/lib/pacman/db.lck'

#continue download
alias wget='wget -c'

#userlist
alias userlist='cut -d: -f1 /etc/passwd'

#merge new settings
alias merge='xrdb -merge ~/.Xresources'

# Aliases for software managment
# pacman or pm
alias pacman='sudo pacman --color auto'
alias update='sudo pacman -Syyu'

# yay as aur helper - updates everything
alias pksyua='yay -Syu --noconfirm'

#ps
alias ps='ps auxf'
alias psgrep='ps aux | grep -v grep | grep -i -e VSZ -e'

#grub update
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'

#improve png
alias fixpng='find . -type f -name "*.png" -exec convert {} -strip {} \;'

#add new fonts
alias fc='sudo fc-cache -fv'

#copy/paste all content of /etc/skel over to home folder - Beware
alias skel='cp -rf /etc/skel/* ~'
#backup contents of /etc/skel to hidden backup folder in home/user
alias bupskel='cp -Rf /etc/skel ~/.skel-backup-$(date +%Y.%m.%d-%H.%M.%S)'

#copy bashrc-latest over on bashrc - cb= copy bash
alias cb='cp ~/.bashrc-latest ~/.bashrc && source ~/.bashrc'

#quickly kill conkies
alias kc='killall conky'

#hardware info --short
alias hw='hwinfo --short'

#skip integrity check
alias yayskip='yay -S --mflags --skipinteg'
alias trizenskip='trizen -S --skipinteg'

#check vulnerabilities microcode
alias microcode='grep . /sys/devices/system/cpu/vulnerabilities/*'

#get fastest mirrors in your neighborhood 
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

#mounting the folder Public for exchange between host and guest on virtualbox
alias vbm="sudo mount -t vboxsf -o rw,uid=1000,gid=1000 Public /home/$USER/Public"

#youtube-dl
alias yta-aac="youtube-dl --extract-audio --audio-format aac "
alias yta-best="youtube-dl --extract-audio --audio-format best "
alias yta-flac="youtube-dl --extract-audio --audio-format flac "
alias yta-m4a="youtube-dl --extract-audio --audio-format m4a "
alias yta-mp3="youtube-dl --extract-audio --audio-format mp3 "
alias yta-opus="youtube-dl --extract-audio --audio-format opus "
alias yta-vorbis="youtube-dl --extract-audio --audio-format vorbis "
alias yta-wav="youtube-dl --extract-audio --audio-format wav "

alias ytv-best="youtube-dl -f bestvideo+bestaudio "

#Recent Installed Packages
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -100"

#Cleanup orphaned packages
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'
