#! /bin/sh

sxhkd &
picom &
flux &
~/blueberry/lemon

bspc monitor -d 1 2 3 4 5

# borders
bspc config border_width          0
#bspc config normal_border_color   "#555555"
#bspc config focused_border_color  "$COLOR_HIGHLIGHT"

# gaps
bspc config window_gap            10
bspc config split_ratio           0.50

# single window layout
bspc config single_monocle        true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
# general
bspc config focus_follows_pointer true

# window specifif
bspc rule -a \*:launchy state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
