#!/bin/bash

# DON"T FORGET TO XRDB -MERGE CURRENT THEME (REWORK THAT)

get_color() {
  # query colors from xrdb
  color=$(xrdb -query | awk '/^\*'$1':(.*)/ { print $2 }')
  echo $color
}

c_red=$(get_color color2)

calc(){ echo $(awk "BEGIN{print $*}"); }
round(){ echo $(echo $1 | awk '{ printf("%d", $1 + 0.5) }'); }

bspc config bottom_padding $PANEL_HEIGHT

get_time(){
  echo $(date "+%I:%M %p")
}

get_focused_window(){
  id=$(bspc query -N -d focused -n .focused.window)
  echo $(xtitle)
}

get_core_load(){
  #phys_core_count=$(lscpu -p | egrep -v '^#' | sort -u -t, -k 2,4 | wc -l)
  load=$(top -d 0.5 -b -n2 | grep "Cpu(s)"| tail -n 1 | awk '{print $2 + $4}')
  blocks="▁▁▂▃▄▅▆▇█"
  result=$(round $(calc $load/12.5))
  echo "%{F$c_red}${blocks:$result:1}%{F-}"
}

_ram() {
  load=$(round $(free | grep Mem | awk '{print $3/$2 * 100 / 10}'))
  bar="%{F$c_red}"
  for i in {0..10}; do
    if [[ $i != $load ]]; then
      bar+="─"
    else
      bar+="%{F-}|"
    fi
  done
  echo $bar
}

while true; do
  echo -e "%{l} $(get_core_load) $(_ram) %{c}$(get_focused_window) $(get_time)"
  sleep 0.5s
done

# ./panel | lemonbar -p -f "TamzenForPowerline:pixelsize=16"
