#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[[ -f $sysresources ]] && xrdb -merge $sysresources
[[ -f "$userresources" ]] && xrdb -merge "$userresources"
[[ -f $sysmodmap ]] && xmodmap $sysmodmap
[[ -f "$usermodmap" ]] && xmodmap "$usermodmap"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#xrdb ~/.Xresources
feh --bg-fill ~/.wallpaper
#exec ~/blueberry/lemon
#exec picom &
#exec flux &
exec bspwm
#exec xterm
