#!/bin/sh

#    ______
#   (, /    )
#     /---(  _   _   , , , ______  __  _.
#  ) / ____)/_)_/_)_(_(_/_/ / / <_/ (_(__
# (_/ (        /
#             '

con() { bspc config "$@"; }
rul() { bspc rule -a "$@"; }
ice() { pkill -x "$1"; { sleep 0.1; "$@"; } ; }

# ------------------------------
#           autostart
# ------------------------------

ice sxhkd &
ice picom &
#ice polybar example &

# custom scripts
ice bspwm-alternating-workspaces 6
ice bspwm-double-borders &
ice bspwm-polybar-workspaces-hook &
ice bspwm-terminal-chomp &

feh --bg-fill ~/Downloads/roujin-z-1.jpg

# ------------------------------
#          wm settings
# ------------------------------

# borders
con border_width                0
con active_border_color         "#00ff00"
con normal_border_color         "#00ff00"
con focused_border_color        "#00ff00"

# gaps
con window_gap                  10

# windows
con split_ratio                 0.50

# single window layout
con single_monocle              true
con borderless_monocle          true
con gapless_monocle             true
con bottom_monocle_padding      0

# general
con focus_follows_pointer       true
con directional_focus_tightness low

# ------------------------------
#        client specific
# ------------------------------

rul \*:launcher state=floating focus=on
rul \*:lantern state=floating
rul \*:calendar-terminal state=floating
rul Zathura state=tiled
rul Kupfer.py focus=on
rul Screenkey manage=off

# godot
rul \*:godot-st desktop=^1
rul \*:Godot_Engine desktop=^1 state=floating
