#!/bin/zsh

#[ -f "$HOME/.config/env" ] && source "$HOME/.config/env"

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

export LESSHISTFILE="-" # disable less search history
export __GL_SHADER_DISK_CACHE_PATH="$XDG_CACHE_HOME"/.nv # nvidia drivers

export EDITOR=nvim
export BROWSER=brave

export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
