#!/bin/bash

source workspace-data

c_1="%{F#ffffff}"
c_2="%{F#888888}"
c_3="%{F#888888}"
c_r="%{F-}"

focused="$(_get_focused_workspace)"

icons=(  ﯜ  )

while read l; do
  IFS=' ' read -r -a l <<< "$l"
  space="${l[0]}"
  value="${l[1]}"

  case $value in
    0)
      [[ "$space" == "$focused" ]] && echo -n "$c_1${icons[0]}$c_r" || echo -n "$c_3${icons[0]}$c_r"
      ;;
    [1-2])
      [[ "$space" == "$focused" ]] && echo -n "$c_1${icons[1]}$c_r" || echo -n "$c_2${icons[1]}$c_r"
      ;;
    *)
      [[ "$space" == "$focused" ]] && echo -n "$c_1${icons[2]}$c_r" || echo -n "$c_2${icons[2]}$c_r"
      ;;
  esac
  echo -n " "
done < <(_get_workspaces)
