#!/bin/bash

if [[ -z $2 ]]; then
  ls "$1/"* | entr ./image-rebuild "$1" "rebuildme"
else
  clear
  echo "CLEAN"
  #podman stop "$1"
  #podman container prune -f
  #sudo rm -rf  ~/.local/share/containers/
  echo
  echo "BUILD"
  podman build -t "$1" "$1"
  echo
  echo "RUN"

  # the null/*-data directory will be on the storage drive under ~/qbittorrent or smth
  # --userns=keep-id
  podman run \
    --rm \
    --userns=keep-id \
    --user qbittorrent \
    --name "$1" \
    -p 8080:8080 \
    -v /home/tsbohc/code/null/qbittorrent-data:/data \
    "$1"
  echo
  echo "EXIT"
fi
