#!/bin/bash

podrun() {
  name=$1 ; shift
  podman run \
    --userns=keep-id \
    --restart unless-stopped \
    --name "$name" \
    "$@" "$name"
}

podrun qbittorrent \
  -p 8080:8080 \
  -v "$HOME/.garden/usr/null/qbittorrent-data:/data"
