#!/bin/sh

# podman save -o qbittorrent-save.tar qbittorrent

podrun() {
  name=$1 ; shift
  podman run \
    --rm \
    --name "$name" \
    "$@" "$name"
}

podrun qbittorrent \
  -p 8080:8080 \
  -v "$HOME/.garden/usr/null/qbittorrent-data:/data"
