#!/bin/bash

define_color() {
  echo "let g:xres_$1='#$2'"
}

background=$(get_xres "background")

if [[ ! -f "/tmp/statusline_colors.vim" ]]; then
  d+="$(define_color "background" $background)"
  d+="
$(define_color "foreground" $(get_xres "foreground"))"
  d+="
$(define_color "lighter_background" $(shade_hex $background 0.7))"
  for i in {9..12}; do
    d+="
$(define_color "color$i" $(get_xres "color$i"))"
  done
  echo "$d" > /tmp/statusline_colors.vim
  echo done
elif ! grep -q "$background" /tmp/statusline_colors.vim; then
  rm /tmp/statusline_colors.vim
  $0
fi
