#!/bin/bash

outer='0x2b2b2c'  # outer
inner1='0xECC679'  # focused
inner2='0x58585a'  # normal

iwidth=1
owidth=1

bspc config border_width $((iwidth + owidth))
bspc config active_border_color "#${inner2:2}"
bspc config normal_border_color "#${inner2:2}"
bspc config focused_border_color "#${inner2:2}"

draw() { chwb2 -I "$inner" -O "$outer" -i "$iwidth" -o "$owidth" "$@" ; }

bspc subscribe node_focus | while read -r event; do
  event_name="$(awk '{ print $1 }' <<< "$event")"
  #wid="$(awk '{ print $4 }' <<< "$event")"
  wid="$(bspc query -N -n .local.descendant_of.window.leaf.!fullscreen)"
  last_wid="$(bspc query -N -n last.!fullscreen)"

  if [[ "$event_name" == "node_focus" ]]; then
    inner="$inner1"
    draw "$wid"

    inner="$inner2"
    draw "$last_wid"
  elif [[ "$event_name" == "node_geometry" ]]; then
    inner="$inner2"
    draw "$wid"

    #inner="$inner1"
    #draw "$last_wid"
  fi
done
