#!/bin/bash

#: get shortcuts and their descriptions from sxhkdrc and pipe them into fzf
#: second line

awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc | column -t -s $'\t' | fzf
