#!/usr/bin/env bash

# herbstluftwm
# ═════════════════════════════════════════════════════════════════

hc() { herbstclient "$@" ; }

ki() { # accept pairs arguments with brace expansion
  for k in "$@"; do echo "$k"; done \
    | awk '{ a[NR]=$0 } END { for (i = 1; i <= NR/2; i++) print a[i]" "a[NR/2+i] }' \
    | while read -r l; do hc keybind $l; done # intentionally unquoted
}

# clean slate
hc emit_hook reload
hc keyunbind --all
hc mouseunbind --all
hc unrule -F
echo -n > ~/.cache/herbstluftwm.log

Super=Mod4
Alt=Mod1
Shift=Shift
Ctrl=Control
Return=Return
Tab=Tab

# TODO add xwallpaper to hori-hori (wallpaper dotfile w/ autostart hook?)
command -v hori &>/dev/null && hori autostart -i
xwallpaper --zoom ~/.garden/usr/wallpaper/roses.jpg

# ........................................................ keybinds

ki $Super-Shift-q "quit"
ki $Super-Shift-r "reload"

# -- frames
ki $Super-Shift-Return "split explode"
ki $Super-r "remove"

ki $Super-{j,l,u,y}         "split  "{left,bottom,top,right}" 0.5"
ki $Super-$Ctrl-{h,n,e,i}   "split "{left,bottom,top,right}" 0.5"

# -- clients
ki $Super-{h,n,e,i}         "focus "{left,down,up,right}
ki $Super-$Shift-{h,n,e,i}  "shift "{left,down,up,right}
ki $Super-$Alt-{h,n,e,i}    "resize "{left,down,up,right}" +0.02"

# -- misc
ki $Super-$Return     "spawn ${TERMINAL:-xterm}"

ki $Alt-$Tab          "spawn hlwm-wfocus"
ki $Alt-$Shift-k      "spawn scribe"
ki $Alt-$Shift-m      "spawn rofm"
ki $Alt-$Shift-s      "spawn scrot-clipboard -q 100 -s"
ki $Super-space       "spawn layout-switch"
ki $Super-BackSpace   "spawn rofi -show run"

ki $Alt-$Shift-{n,e}  "spawn redshift-control 0 "{-1,1}
ki $Alt-{n,e}         "spawn redshift-control "{-250,250}
# ki $Alt-[h,i] spawn volume-control [-8,8]

for i in {1..9}; do hc add "$i"; done
ki $Super-{1,2,3,4,5,6,7,8,9}          "use_index "{0,1,2,3,4,5,6,7,8}
ki $Super-$Shift-{1,2,3,4,5,6,7,8,9}  "move_index "{0,1,2,3,4,5,6,7,8}

# ki $Super-{1,2,3,4,5,6,7,8,9}          "spawn hlwm-index use "{0,1,2,3,4,5,6,7,8}
# ki $Super-$Shift-{1,2,3,4,5,6,7,8,9}  "spawn hlwm-index move "{0,1,2,3,4,5,6,7,8}


# layouts
ki $Super-m "fullscreen toggle"
ki $Super-p "pseudotile toggle"
ki $Super-f "floating toggle"

ki $Super-f "set_attr clients.focus.floating toggle"


# mouse
hc mousebind $Super-Button1 move
hc mousebind $Super-Button2 zoom
hc mousebind $Super-Button3 resize

# ..................................................... miniscripts

close_window_or_frame=(
or . and - compare tags.focus.curframe_wcount gt 0
         - close
   . remove)

ki $Super-w "${close_window_or_frame[*]}"

cycle_layouts=(
and . compare tags.focus.curframe_wcount gt 1
    . cycle_layout +1 vertical horizontal)

ki $Super-Tab "${cycle_layouts[*]}"

# ........................................................... theme

hc set smart_window_surroundings off # remove window borders and gaps when only one window in frame
hc set smart_frame_surroundings on # shouldn't this disable... frame_color too?

# gaps
hc set frame_gap 2
hc set window_gap 5
hc set frame_padding 0

# frames
# hc set frame_bg_normal_color '#cccccc50'
# hc set frame_normal_opacity 15
#
# hc set frame_bg_active_color '#cccccc50'
# hc set frame_active_opacity 30
#
# hc set frame_border_width 2
# hc set frame_border_inner_width 1
#
# hc set frame_border_normal_color '#000000'
# hc set frame_border_active_color '#000000'
#
# hc set frame_border_inner_color '#ffffff'

# no borders, flat
hc set frame_bg_normal_color '#cccccc50'
hc set frame_normal_opacity 15

hc set frame_bg_active_color '#cccccc50'
hc set frame_active_opacity 40

hc set frame_border_width 0
hc set frame_border_inner_width 0

hc set frame_border_normal_color '#000000'
hc set frame_border_active_color '#000000'

hc set frame_border_inner_color '#ffffff'

# single border
# hc set frame_bg_normal_color '#cccccc50'
# hc set frame_normal_opacity 15
#
# hc set frame_bg_active_color '#cccccc50'
# hc set frame_active_opacity 30
#
# hc set frame_border_width 1
# hc set frame_border_inner_width 1
#
# hc set frame_border_normal_color '#ffffff'
# hc set frame_border_active_color '#ffffff'
#
# hc set frame_border_inner_color '#ffffff'

# hc set frame_border_width 0
# hc set frame_border_inner_width 0


hc set always_show_frame true
hc set frame_bg_transparent false # recommended off
#hc set frame_transparent_width 2 # depends on the above being true

# clients
attr() { hc attr "$@" ; }

attr theme.tiling.reset 1
attr theme.floating.reset 1

attr theme.border_width 2
attr theme.inner_width 1
attr theme.outer_width 1
attr theme.inner_color '#333333'
attr theme.outer_color '#000000'
attr theme.active.inner_color '#555555'

# attr theme.border_width 7
# attr theme.outer_width 6
# attr theme.inner_width 1
# attr theme.inner_color '#333333'
# attr theme.outer_color '#1F1F1F'
# attr theme.active.inner_color '#555555'




#hc attr theme.floating.border_width 2
#hc attr theme.floating.inner_width 1

#hc attr theme.floating.outer_width 8

#hc attr theme.background_color '#ffffff'
#hc attr theme.inner_color '#ffffff'
#hc attr theme.outer_color '#ffffff'
#hc attr theme.title_color '#ffffff'

#hc attr theme.floating.background_color '#ff0000'
#hc attr theme.floating.inner_color '#323235'
#hc attr theme.floating.outer_color '#232326'

#hc attr theme.floating.active.inner_color '#636369'
#hc attr theme.floating.active.outer_color '#232326'

#hc attr theme.floating.title_color '#ff0000'

#hc attr theme.title_height 15
##hc attr theme.title_font 'Dejavu Sans:pixelsize=12'  # example using Xft
#hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
#hc attr theme.padding_top 2  # space below the title's baseline (i.e. text depth)
#hc attr theme.active.color '#345F0Cef'
#hc attr theme.title_color '#ffffff'
#hc attr theme.normal.color '#323232dd'
#hc attr theme.urgent.color '#7811A1dd'
#hc attr theme.normal.title_color '#898989'
#hc attr theme.inner_width 1
#hc attr theme.inner_color black
##hc attr theme.border_width 1
##hc attr theme.floating.border_width 4
##hc attr theme.floating.outer_width 1
##hc attr theme.floating.outer_color black
#hc attr theme.active.inner_color '#789161'
#hc attr theme.urgent.inner_color '#9A65B0'
#hc attr theme.normal.inner_color '#606060'
## copy inner color to outer_color
#for state in active urgent normal ; do
#    hc substitute C theme.${state}.inner_color \
#        attr theme.${state}.outer_color C
#done
#hc attr theme.active.outer_width 1
#hc attr theme.background_color '#141414'

#hc set mouse_recenter_gap 0
#hc set focus_follows_mouse false

# ........................................................... rules

hc rule hook=node_add focus=on
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule title='floaterm' floating=on floatplacement=center focus=on
hc rule class='love' floating=on floatplacement=center focus=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

hc unlock # important?
hc set_monitors 1920x1080+0+0 1920x1080+1920+0
