#!/bin/bash

# $1 - fre
# $2 - data
awk -F"|" '
  FNR==NR {
    a[$1]=$2;next
  }
  {
    if ( $1 in a ) {
      print a[$1]"|"$1" — "$2
    } else {
      print "0|"$1" — "$2
    }
  }' "$1" "$2" | sed -e "s///" | sort -k1,1nr | awk -F"|" '{print $2}'
