#!/bin/bash

xbacklight -inc $1
if [ $1 -gt 0 ]; then
  change="+$1"
else
  change=$1
fi

brightness=$(xbacklight -get | awk '{print int(($1+0.5)/5)}')

for i in {0..20}; do
  if [[ $i == $brightness ]]; then
    bar=$bar"|"
  else
    bar=$bar"-"
  fi
done

dunstify "brightness $change" -b "\\$bar" -r "991049"
