#!/bin/bash

cat output_50k | fzf --info=hidden --no-multi --reverse --ansi --no-sort --exact --no-hscroll \
  --color=bg:-1,bg+:-1,gutter:-1,hl:15,hl+:15,fg:7,fg+:7,info:7,prompt:7,pointer:4,header:15
