#!/bin/bash

ENV="$HOME/.garden/etc"
colo="kohi"

cherry-blossom() {

  with $colo; lyn alacritty
  lyn bspwm
  lyn sxhkd

  #lyn xinitrc ~/.xinitrc
}

cherry-library() {
  local CONF="$HOME/.config"

  # id          source file      symlink target
  - alacritty  "alacritty.yml"  "$CONF/alacritty/alacritty.yml"
  - bspwm      "bspwmrc"        "$CONF/bspwm/bspwmrc"
  - sxhkd      "sxhkdrc"        "$CONF/sxhkd/sxhkdrc"
}

#shell() {
#  case "$1" in
#    bash)
#      lyn bashrc ~/.bashrc
#      lyn aliases ~/.aliases
#      ;;
#    zsh)
#      lyn zshrc ~/.zshrc
#      ;;
#  esac
#}
#
#dtenv() {
#  case "$1" in
#    bspwm)
#      lyn bspwmrc ^/bspwm/bspwmrc
#      lyn sxhkdrc ^/sxhkd/sxhkdrc
#      ;;
#  esac
#}
