#!/bin/bash
# {{{
# cherry is a .files management api that features templating and database querying
# blossom is its accompanying configuration framework inspired by vim plugin managers

# go further than variables into code chunk injection?
# like what wm to start in xinitrc

# --clean
# look through links db and remove whatever is not in ly
# --query
# get values form colors or specified varset
# }}}

source cherry; blossom() {
  colors="whoah"

  # term
  wi $colors; lyn alacritty

  # wm
  #yay -S bspwm sxhkd
  lyn bspwm
  lyn sxhkd

  # other
  #ex module
}

module() {
  echo "i'm a module"
}

# parse options here

blossom
