#!/bin/bash

. varset
varset::load links

action="install"
current_varsets=()
clean_whitelist=()

# {{{ inspect
inspect() {
  # print associative array k, v pairs
  local -n ref=$1
  echo
  echo "inspect: $1"
  for k in "${!ref[@]}" ; do
    echo "$k : ${ref[$k]}"
  done
}
# }}}

# {{{
install?() {
  [[ "$action" == "install" ]] && return 0 || return 1
}

clean?() {
  [[ "$action" == "clean" ]] && return 0 || return 1
}
# }}}

wi() {
  current_varsets=( "$@" )
}

lyn() {
  if install?; then
    # TODO: check if link is defined
    #                source file exists

    data=(${links["$1"]}) # no quotes to expand string into array
    source="${data[0]}"
    target="${data[1]}"
    [[ "${target:0:1}" == '^' ]] && target="$HOME/.config${target:1}"
    echo "$1: from $source to $target with ${current_varsets[@]}"

    for varset in "${current_varsets[@]}"; do
      varset::load "$varset"
      declare -n varset_ref="$varset"
      for key in "${!varset_ref[@]}"; do
        find="@}:-$key-:{@"
        subs="${varset_ref["$key"]}"
      done
    done
    current_varsets=()
  elif clean?; then
    clean_whitelist+=( "$1" )
  fi
}

# wrap for logging and consistency
ex() {
  echo "run module $1"
}
