#!/bin/bash

# varset syntax is basically xresources, which makes it easy to adapt themes
# and gives us syntax highlighting!

varset::load() {
  # load varset $1 into a respective assoc array
  declare -n ref="$1"
  declare -gA "$1"

  while IFS=: read key value ; do
    [ -z "$key" ] && continue
    [[ "${key:0:1}" == "!" ]] && continue
    value="${value#"${value%%[![:space:]]*}"}"
    ref["$key"]="$value"
  done < varsets/"$1"
}

varset::query() {
  # retrieve value of key $2 from varset $1
  declare -n ref="$1"
  echo "${ref["$2"]}"
}
