#!/bin/sh

#    ______
#   (, /    )
#     /---(  _   _   , , , ______  __  _.
#  ) / ____)/_)_/_)_(_(_/_/ / / <_/ (_(__
# (_/ (        /
#             '

_c() { bspc config "$@"; }
_r() { bspc rule -a "$@"; }
_s() { pkill -x "$1"; { sleep 0.1; "$@"; } & }

# autostart
_s sxhkd
_s bspwm-blocks
_s bspwm-chomp
_s picom

_set_workspaces() { # {{{
  # alternates workspaces across monitors
  # $1 - desired number of workspaces
  declare -A workspaces
  monitor_names="$(bspc query -M --names)"

  i=1
  while (( "$i" <= "$1" )); do
    while read m; do
      workspaces["$m"]="${workspaces[$m]}${i} "
      i=$[$i+1]
    done <<< "$monitor_names"
  done

  while read m; do
    bspc monitor "$m" -d ${workspaces[$m]}
  done <<< "$monitor_names"
} # }}}
_set_workspaces 6

# borders
_c border_width          1
_c active_border_color   "#1d2021"
_c normal_border_color   "#1d2021"
_c focused_border_color  "#1d2021"

# gaps
_c window_gap            10

# windows
_c split_ratio           0.50

# single window layout
_c single_monocle        true
_c borderless_monocle    true
_c gapless_monocle       true

# general
_c focus_follows_pointer true

# window specific
_r \*:launcher state=floating focus=on
_r Zathura state=tiled
_r Kupfer.py focus=on
_r Screenkey manage=off
