#!/bin/sh

#    ______
#   (, /    )
#     /---(  _   _   , , , ______  __  _.
#  ) / ____)/_)_/_)_(_(_/_/ / / <_/ (_(__
# (_/ (        /
#             '

# modules are located in the git repo, not symlinked to ~/.config/bspwm/modules
DIR="$(cd "$(dirname "$(realpath "$0")")" && pwd)"

_c() { bspc config "$@"; }
_r() { bspc rule -a "$@"; }
_s() { pkill -x "$1"; { sleep 0.1; "$@"; } & }
_m() { _s "$DIR/modules/$@"; }

# autostart
_s sxhkd
_s picom
_s polybar example

# modules
_m alternating-workspaces 6
_m polybar-workspaces-hook
_m terminal-chomp

#bspc monitor -d 1 2 3 4

# borders
_c border_width          1
_c active_border_color   "#1d2021"
_c normal_border_color   "#1d2021"
_c focused_border_color  "#1d2021"

# gaps
_c window_gap            10

# windows
_c split_ratio           0.50

# single window layout
_c single_monocle         true
_c borderless_monocle     true
_c gapless_monocle        true
_c bottom_monocle_padding 0

# general
_c focus_follows_pointer true

# window specific
_r \*:launcher state=floating focus=on
_r \*:lantern state=floating
_r \*:calendar-terminal state=floating
_r Zathura state=tiled
_r Kupfer.py focus=on
_r Screenkey manage=off
