directory: /data/mus
library: /data/mus/.lib

paths:
  default: %lower{$albumartist - $album%aunique{}/$track $title}
  singleton: %lower{misc/$artist/$title}
  comp: %lower{comp/$album%aunique{}/$track $title}

import:
  move: yes
  languages: en
