#!/bin/bash

d=""

declare -a common_fzf_options=(
  --no-info
  --no-multi
  --no-sort
  --reverse
  --delimiter="$d"
  --prompt="  "
  --pointer="◇"
  --preview-window=wrap:noborder:down
  #--bind="enter:execute!cp out/{} current!"
  --preview="cat out/{}"
  #viu -w 60 yttmb/{}.jpg ; echo ; 
  #--with-nth=1..2 # visible fields
  #--nth=2         # search fields relative to the above
)

python yt.py
o="$(ls out -t | fzf "${common_fzf_options[@]}")"

[[ "$o" == "" ]] && exit

url="$(awk 'END { print }' "out/$o")"

# feh --auto-reload

if [[ "$url" =~ "youtube.com" || "$url" =~ "v.redd.it" ]]; then
  mpv "$url"
elif [[ "$url" =~ "i.redd.it" ]]; then
  feh --scale-down --auto-zoom "$url"
else
  brave "$url"
fi
