#!/bin/bash

d=""

declare -a common_fzf_options=(
  --no-info
  --no-multi
  --no-sort
  --reverse
  --delimiter="$d"
  --prompt="  "
  --pointer="◇"
  --preview-window=wrap
  --preview="viu -w 60 yttmb/{}.jpg ; echo ; cat out/{}"
  #--with-nth=1..2 # visible fields
  #--nth=2         # search fields relative to the above
)

python yt.py
o="$(ls out -t | fzf "${common_fzf_options[@]}")"

url="$(awk 'END { print }' "out/$o")"

[[ "$url" != "" ]] && mpv "$url"
