#!/bin/bash

declare -a fzf_options=(
    --no-unicode
    --no-info
    --no-multi
    --no-sort
    --reverse
    --border
    --delimiter=" "
    --prompt="> "
    --pointer=">"
    --color=bg:-1,bg+:-1,hl:15,hl+:15,fg:7,fg+:7,info:7,prompt:7,pointer:4,header:15
    --margin=1,2
    --with-nth=1,2
    --expect "enter,esc"
  )

# expect ctrl-r reload trick

out="$(cat cache | sort -t -k3 -n -r | fzf "${fzf_options[@]}")"

mapfile -t out <<< "$out"
key="${out[0]}"

case "$key" in
  "enter")
    url="$( awk -F" " '{ print $4 }' <<< "${out[1]}")"
    [[ "$url" != "" ]] && mpv "$url" >/dev/null
    ./$(basename $0)
    ;;
  "esc")
    exit 0
    ;;
esac

