#!/bin/bash

input="$(<"conf.yaml")"

#awk -F"[ ]" '{for(i=1;i<=NF && ($i=="");i++);print "there are "i-1" spaces leading upto " $0}' conf.yaml
#sed -e "s|^\($s\):|\1|" conf.yaml
awk '{
   match($0, /^ */);
   print RLENGTH" "substr($0,RLENGTH+1)
 }'
