#!/bin/bash

# add command history
# remove compgen
# store all typed commands into a file, use that as data
# if the entered command isn't in the below definitions, run it within the launcher terminal and exit
# maybe store data as priority|name

IFS='' read -r -d '' not_terminal << "EOF"
discord
brave
redshift
EOF

IFS='' read -r -d '' terminal << "EOF"
sdlfasldfja
EOF

IFS='' read -r -d '' browser << "EOF"
r/all
r/unixporn
r/funny
r/mechanicalkeyboards
google.com
EOF

# remember to set a floating rule in the wm
WINDOW_NAME="launcher"

tag_reddit="rddt"
tag_browser="brws"
tag_terminal="term"
tag_gui="grfx"
tag_default="dflt"

_init() {
  xdotool search --onlyvisible --classname $WINDOW_NAME windowunmap \
    || xdotool search --classname $WINDOW_NAME windowmap \
    || st -n $WINDOW_NAME -a -g "35x7+0+0" -e "$0" "$@"
}

desktop_applications=$(find /usr/share/applications/ -maxdepth 1 -type f -name '*.desktop' | sort | awk -F/ '{print $NF}' | cut -d'.' -f1)

# black magic
_fzf() {
  fzf +m \
    --preview="
if grep -qFx {} <<< '${browser}'; then
  if [[ {} == 'r/'* ]]; then
    echo '${tag_reddit}'
  else
    echo '${tag_browser}'
  fi
elif grep -qFx {} <<< '${not_terminal}'; then
  echo '${tag_gui}'
elif grep -qFx {} <<< '${terminal}'; then
  echo '${tag_terminal}'
elif grep -qFx {} <<< '${desktop_applications}'; then
  if grep -q 'Terminal=false' /usr/share/applications/{}.desktop; then
    echo '${tag_gui}'
  else
    echo '${tag_terminal}'
  fi
#else
#  echo '${tag_default}'
fi
  " --preview-window=right:2:noborder:wrap \
    --bind=change:top \
    --reverse --no-info --margin 2 --prompt="$ " \
    --color="bg:-1,bg+:-1,gutter:-1,hl:15,hl+:15,fg:7,fg+:7,prompt:2,pointer:8,header:7,preview-fg:8" \
    "$@"
}

_decide() {
  if grep -qFx "$1" <<< "${browser}"; then
    if [[ "$1" == "r/"* ]]; then
      echo "${tag_reddit}"
    else
      echo "${tag_browser}"
    fi
  elif grep -qFx "$1" <<< "${not_terminal}"; then
    echo "${tag_gui}"
  elif grep -qFx "$1" <<< "${terminal}"; then
    echo "${tag_terminal}"
  elif grep -qFx "$1" <<< "${desktop_applications}"; then
    if grep -q "Terminal=false" "/usr/share/applications/${1}.desktop"; then
      echo "${tag_gui}"
    else
      echo "${tag_terminal}"
    fi
  else
    echo "${tag_default}"
  fi
}

_get_choices() {
  local choices
  choices+=$(compgen -c)
  # needed to separate lists
  choices+="
"

  #choices+=$(ls -A)
  #choices+=""
  choices+=$browser
  printf '%s\n' "$choices"
}

# launch applications based on the above
_run_application() {

  _detach_process() {
    exec setsid "$@"
  }

  local decision=$(_decide "$1")

  case "$decision" in
    "$tag_gui")
      _detach_process "$1"
      ;;
    "$tag_terminal")
      _detach_process st -e "$1"
      ;;
    "$tag_browser")
      _detach_process brave "$1"
      ;;
    "$tag_reddit")
      _detach_process brave "old.reddit.com/${1}"
      ;;
    *)
      sleep 1s
      ;;
  esac
}

case "$1" in
  _run)
    choice=$(_get_choices | _fzf) && _run_application "$choice"
    ;;
#  run)
#    _init _run
#    ;;
  *)
    _init _run
    echo "noarg"
    exit 1
    ;;
esac
