#!/bin/bash

t_min=1000
t_max=6500
b_min=1
b_max=10

temp_file="/tmp/red-control"

# get current values
if [ -f "$temp_file" ]; then
  t=$(awk 'NR==1 {print; exit}' "$temp_file")
  b=$(awk 'NR==2 {print; exit}' "$temp_file")
else
  t="$t_max"
  b="$b_max"
fi

# apply deltas
[[ -n "$1" ]] && t=$(( "$t" + "$1" ))
[[ -n "$2" ]] && b=$(( "$b" + "$2" ))

# cap values
(( "$t" > "$t_max" )) && t="$t_max"
(( "$t" < "$t_min" )) && t="$t_min"
(( "$b" > "$b_max" )) && b="$b_max"
(( "$b" < "$b_min" )) && b="$b_min"

# dunst
t_bar=$(hbar "$t" "$t_max" 13 "─" "┘" "─")
dunstify "redshift" "${t}K "$t_bar" ${b}0%" -r 93437187 -t 2000

# overwrite file contents
> "$temp_file"
echo "$t" >> "$temp_file"
echo "$b" >> "$temp_file"

# format brightness
(( "$b" > "9" )) && b="1.0" || b="0.${b:0:1}"

# execute
redshift -P -O "$t" -b "$b"
