#!/bin/bash

_lantern() { # $1 - option
  [[ $# == 0 ]] && opt=c || opt=$1
  case $opt in
    c)
      _lantern_fzf_margin="--margin=1,2"
      _lantern_fzf_height="--height=10"
      main ;;
    w)
      xdotool search --onlyvisible --classname "lantern" windowunmap \
        || xdotool search --classname "lantern" windowmap \
        || st -n "lantern" -a -g "35x7+0+0" -e "_lantern ; sleep 3s" ;;
    i)
      _lantern_fzf_height="--height=100"
      _lantern_fzf_margin="--margin=2"
      main ;;
    h|help)
      echo "usage" ;;
    *)
      sleep 2s
      echo hey
      return ;;
  esac
}
