#!/bin/bash

hook() {
  find "$@" -iname "*$in*"
}

MINLEN=1

while read -n 1 -s i; do

  n="$(echo -n $i|od -i -An|tr -d " ")"

  if (( $n == 127 )); then # backspace
    if (( ${#in} > 0 )); then
      in=${in:0:${#in}-1}
    fi
  elif (( $n == 27 )); then # escape...
    exit 0
  else
    in=$in$i
  fi

  clear
  echo ":: $in"

  if (( ${#in} >= $MINLEN )); then
    hook
  fi
done
