#!/usr/bin/env bash

##terminalFilter

del=`printf "\x7f"` #backspace character

input="`cat`"       #create initial set from all input
#take the filter macro from the first argument or use
# 'grep -F "$pattern"'
filter=${1:-'grep -F "$pattern"'}  
pattern=  #what's inputted by the keyboard at any given time

printSelected(){
  echo "$input" | eval "$filter"
}
printScreen(){
  clear
  printSelected
  #Print search pattern at the bottom of the screen
  tput cup $(tput lines);  echo -n "PATTERN: $pattern"
} >/dev/tty   
#^only the confirmed results go `stdout`, this goes to the terminal only

printScreen
#read from the terminal as `cat` has already consumed the `stdin`
exec 0</dev/tty
while IFS=$'\n' read -s -n1 key; do
  case "$key" in 
    "$del") pattern="${pattern%?}";;  #backspace deletes the last character
        "") break;; #enter breaks the loop
         *) pattern="$pattern$key";; #everything else gets appended 
                                     #to the pattern string
  esac
  printScreen
done

clear
printSelected
