#!/usr/bin/env bash

function init() {
  data=$(cat "$DATA_PATH")
  [[ $# == 0 ]] && opt=c || opt=$1
  case $opt in
    c)
      launch
      ;;
    w)
      st -e "$0" i
      ;;
    i)
      launch
      ;;
    g)
      clean
      ;;
    *)
      echo "usage"
      sleep 1s
      exit 1 ;;
  esac
}

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/config.sh"

launch() {
  echo $opt
  search
  echo launch
  sleep 1s
}

search() {
  # find all non-hidden folders in home, remove ~ itself
  home_dirs="$(find ~ -maxdepth 1 -not -path '*/\.*' -type d | sed '1d')"
  # separate into lines
  home_dirs="${home_dirs//$'\n'/ }"
  # find all files in those folders
  home="$(find $home_dirs \( -name .git \) -prune -o -print)"
  # add files from ~
  home+="$(find ~ -maxdepth 1 -type f)"

  # decide on default action for each file
  while IFS= read -r l; do
    if [[ -d "$l" ]]; then
      m="d"
    elif [[ -x "$l" ]]; then
      m="x"
    else
      m="f"
    fi
    l=${l/#$HOME/'~'}
    add_entry "$m" "$l"
  done <<< "$home"

  # sort and ignore duplicates based on $col
  data=$(echo "$data" | sort -k1,1nr | awk -F"$d" '!x[$3]++')
}

WINDOW_NAME="lantern"
DATA_PATH="$HOME/blueberry/sandbox/lantern.d/data"
d=" " # this is &nbsp;

init $@
