#!/bin/bash

move_amount=60
size_amount=20

if [ "$1" == "m" ]; then
  if bspc query -N -n focused.tiled ; then
    case $2 in
      "h") bspc node --swap west --follow ;;
      "l") bspc node --swap east --follow ;;
      "j") bspc node --swap south --follow ;;
      "k") bspc node --swap north --follow ;;
    esac
  elif bspc query -N -n focused.floating ; then
    case $2 in
      "h") bspc node --move -$move_amount 0 ;;
      "l") bspc node --move $move_amount 0 ;;
      "j") bspc node --move 0 $move_amount ;;
      "k") bspc node --move 0 -$move_amount ;;
    esac
  fi
elif [ "$1" == "r" ]; then
  if bspc query -N -n focused.tiled ; then
    case $2 in
      "h") bspc node -z right -$size_amount 0 || bspc node -z left -$size_amount 0 ;;
      "l") bspc node -z right $size_amount 0 || bspc node -z left $size_amount 0 ;;
      "j") bspc node -z top 0 $size_amount || bspc node -z bottom 0 $size_amount ;;
      "k") bspc node -z bottom 0 -$size_amount || bspc node -z top 0 -$size_amount ;;
    esac
  elif bspc query -N -n focused.floating ; then
    case $2 in
      "h") bspc node -z right -$move_amount 0 ;;
      "l") bspc node -z right $move_amount 0 ;;
      "j") bspc node -z bottom 0 $move_amount ;;
      "k") bspc node -z bottom 0 -$move_amount ;;
    esac
  fi
fi
