#!/bin/bash

#outer='0x050505'  # outer
#inner1='0x665c54'  # focused
#inner2='0x3c3836'  # normal

outer='0x323d43'  # outer
inner1='0xa7c080'  # focused
inner2='0x868d80'  # normal

iwidth=2
owidth=6

bspc config border_width $((iwidth + owidth))
bspc config active_border_color "#${outer:2}"
bspc config normal_border_color "#${outer:2}"
bspc config focused_border_color "#${outer:2}"

draw() { chwb2 -I "$inner" -O "$outer" -i "$iwidth" -o "$owidth" "$@" >/dev/null 2>&1 ; }

bspc subscribe node_geometry node_focus | while read -r event; do
  if [[ "$event_name" == "node_focus" ]]; then
    wid="$(awk '{ print $4 }' <<< "$event")"
    inner="$inner1"
    draw "$wid"
done

#outer='0x323d43'  # outer
#inner1='0xa7c080'  # focused
#inner2='0x868d80'  # normal
#
#iwidth=2
#owidth=6
#
#bspc config border_width $((iwidth + owidth))
#bspc config active_border_color "#${outer:2}"
#bspc config normal_border_color "#${outer:2}"
#bspc config focused_border_color "#${outer:2}"
#
#draw() { chwb2 -I "$inner" -O "$outer" -i "$iwidth" -o "$owidth" "$@" >/dev/null 2>&1 ; }
#
#bspc subscribe node_geometry node_focus | while read -r event; do
#  event_name="$(awk '{ print $1 }' <<< "$event")"
#  wid="$(awk '{ print $4 }' <<< "$event")"
#  last_wid="$(bspc query -N -n last)"
#
#  if [[ "$event_name" == "node_focus" ]]; then
#    inner="$inner1"
#    draw "$wid"
#
#    inner="$inner2"
#    draw "$last_wid"
#  elif [[ "$event_name" == "node_geometry" ]]; then
#    inner="$inner2"
#    draw "$wid"
#
#    inner="$inner1"
#    draw "$last_wid"
#  fi
#done
