#!/bin/bash

# running things concurrently helps alleviate window flickering

# polybar wisible in tiled only, auto-monocle
# - if ^2 monitor is in monocle/has 1 window it expands weirdly and gets cut off by a bit when polybar is visible

#if [[ "$1" == "1" ]]; then
#  bspc config single_monocle true &
#  polybar-msg cmd show >/dev/null
#  bspc config -m ^1 bottom_padding 15 &
#  bspc config -m ^1 bottom_monocle_padding -15 &
#else
#  bspc config single_monocle true &
#  bspc config -m ^1 bottom_padding 0 &
#  bspc config -m ^1 bottom_monocle_padding 0 &
#  polybar-msg cmd hide >/dev/null
#fi

# polybar visible in tiled only, good for non-auto monocle
# + monocle and desktop with 1 window are distinguishable
# + monocle is still true 100% full screen
# - if ^2 monitor is in monocle it expands weirdly and gets cut off by a bit when polybar is visible, less noticible as no auto-monocle

if [[ "$1" == "1" ]]; then
  polybar-msg cmd show >/dev/null
  bspc config gapless_monocle true &
  bspc config single_monocle false &
  bspc config -m ^1 bottom_padding 15 &
  bspc config -m ^1 bottom_monocle_padding -15 &
else
  bspc config gapless_monocle true &
  bspc config single_monocle false & # can't switch to true as both monitors are affected and that makes it jitter esp if browser is on second monitor alone
  bspc config -m ^1 bottom_padding 0 &
  bspc config -m ^1 bottom_monocle_padding 0 &
  polybar-msg cmd hide >/dev/null
fi

# polybar visible in tiled/monocle
# meh

#if [[ "$1" == "1" ]]; then
#  polybar-msg cmd show >/dev/null
#  bspc config single_monocle true &
#  bspc config -m ^1 bottom_padding 15 &
#  bspc config -m ^1 bottom_monocle_padding 0 &
#  bspc config gapless_monocle false &
#else
#  bspc config single_monocle true &
#  bspc config -m ^1 bottom_padding 0 &
#  bspc config gapless_monocle true &
#  polybar-msg cmd hide >/dev/null
#fi
