#!/bin/bash

if [[ "$1" == "1" ]]; then
  polybar-msg cmd show >/dev/null
  # running those two concurrently helps alleviate window flickering
  bspc config -m ^1 bottom_padding 15 &
  bspc config -m ^1 bottom_monocle_padding -15 &
else
  bspc config -m ^1 bottom_padding 0
  bspc config -m ^1 bottom_monocle_padding 0
  polybar-msg cmd hide >/dev/null
fi
