#!/bin/bash

bspc subscribe node_remove | while read -r event; do
  event_name="$(awk '{ print $1 }' <<< "$event")"

  if [[ "$event_name" == "node_remove" ]]; then
    wid="$(awk '{ print $4 }' <<< "$event")"
    did="$(awk '{ print $3 }' <<< "$event")"

    bspc node last -i
  fi
done
