#!/bin/bash

#: list shell scripts and their descriptions

grep ^'#:' -Ir ~/.garden/src ~/.garden/bin | awk -F":#:" '{ print $1"	"$2 }' | column -t -s $'\t' | fzf

# TODO
# when pressing enter on a script, rg for its usage in the repo
# would be really nice for keeping track of names and figuring out useless scripts
# would be doubly effective if i prefixed each script with s: or something, e.g s:layout-switch
# that way it'll probably be 99% right

# calling the scripts would be awfully inconvenient without aliases though...

# TODO on another not, i should look into have a better way of opening files in vim

# i could even render a dependency tree if i wanted (course i do)
