#!/bin/sh

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

xresources=$HOME/.config/x11/.Xresources
xmodmap=$HOME/.config/x11/.Xmodmap

[ -f "$xresources" ] && xrdb -merge "$xresources"
[ -f "$xmodmap" ] && xmodmap "$xmodmap"

autostart="pipewire pipewire-pulse mpd"
for program in $autostart; do
  pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

xset r 66 # repeat caps lock
xset r rate 250 36 # set key repeat rate: 250ms delay, 40/s

setxkbmap us -variant colemak

exec dbus-run-session herbstluftwm --locked
