#!/usr/bin/env bash

H="%{F#ffffff}"
M="%{F#888888}"
L="%{F#666666}"
R="%{F-}"

herbstclient --idle "tag_*" 2>/dev/null | {
  while true; do
    IFS=$'\t' read -ra tags <<< "$(herbstclient tag_status)"
    {
      echo " "
      for i in "${tags[@]}" ; do
        case ${i:0:1} in
          '.') # the tag is empty
            echo "$L·$R " ;;
          ':') # the tag is not empty
            echo "$L◇$R " ;;
          '+') # the tag is viewed on the specified MONITOR, but this monitor is not focused.
            echo "+ " ;;
          '#') # the tag is viewed on the specified MONITOR and it is focused.
            echo "$H◆$R " ;;
          '-') # the tag is viewed on a different MONITOR, but this monitor is not focused.
            echo "$H◇$R " ;;
          '%') # the tag is viewed on a different MONITOR and it is focused.
            echo "% " ;;
          '!') # the tag contains an urgent window
            echo "⇌ " ;;
        esac
      done
      echo "%{F-}%{B-}"
    } | tr -d "\n"
    echo
    read -r || break
  done
} 2>/dev/null
