#!/bin/bash

declare -A icons=(
  ["sunny"]=""
  ["clear"]=""
  ["clear/sunny"]=""
  ["cloudy"]=""
  ["partly cloudy"]=""
  ["parftial fog, fog"]=""
  ["overcast"]=""
)

if ping -q -w1 -c1 google.com &>/dev/null ; then
  o="$(curl --silent --compressed wttr.in/~59.9387318,30.3162286?format="%C:%f\n")"

  condition="$(awk -F":" '{ print tolower($1) }' <<< "$o")"
  feels_like="$(awk -F":" '{ print $2 }' <<< "$o")"

  echo "$condition $feels_like ${icons[$condition]} "
else
  echo "N/A"
fi
